### ISSUE TITLE
Crash with DW20 1.7.10 Pack v.1.0.2

### ISSUE THREAD

**Issue by Hades99** [ollieread/TechnoMagi#13]
I was just wondering if you have tried your mod with Thaumcraft or Biomes O Plenty because both seem to have problems with the new perception filter/saved state dimension

**Comment by ollieread** [comment]
In what way?

**Comment by Hades99** [comment]
basically what happens during world loading is your mod tries to grab the
seed world for the perception things but as that's happening thaumcraft is
generating its aura nodes and the two say to each other (i'm not feeling
this today) and the game crashes. I think it just has a problem with tile
entities.

i will post logs tonight

On Wed, Jan 28, 2015 at 7:01 PM, Ollie Read <notifications@github.com>
wrote:

> In what way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ollieread/TechnoMagi/issues/13#issuecomment-71949682>.
>



-- 
Eli

**Comment by ollieread** [comment]
Strange, though after inspecting, I suspect that the issue is Thaumcraft, as rather than generate the nodes during world generation, it generates them during chunk loading, which is completely and utterly wrong, that's annoying. Perhaps I'll have to force the perception filters to not work if Thaumcraft is present :(

**Comment by ollieread** [comment]
Do you have the log?
