### ISSUE TITLE
Server Startup Crash

### ISSUE THREAD

**Issue by mtac002** [ollieread/TechnoMagi#26]
I can't fix this so I will post it here for some help. I am hosting it here for the talks about the mod and no other. http://pastebin.com/3kJFAr4Z

**Comment by ollieread** [comment]
That's a really weird error, it looks like something is trying to access the block icons on the server side, but I'm struggling to recreate this. Will look into it further this evening once I've finished work.

**Comment by kindlich** [comment]
I have the same Crash!
I also tested it with only technoMagi and the cofh-core and cofh-lib installed...
btw mtac002 and I are running the newest forge version for 1.7.10 (1403 at the end)

**Comment by ollieread** [comment]
Alright thanks, this is actually built with 10.13.2.1291 but I'm taking a look further into this to try and figure out what's going on....

When you say, 'Server Startup Crash' does this mean you can run it perfectly locally, in the client, but specifically when on a dedicated server it crashes?

**Comment by ollieread** [comment]
With a little help I figured this out, hotfix build: 0.5.2.29-alpha.

http://minecraft.curseforge.com/mc-mods/223235-technomagi/files/2237851

**Comment by mtac002** [comment]
Yes that is what I meet I can run a single player world fine but can't run
the server.

**Comment by ollieread** [comment]
FYI: If you're interested, the problem was that when declaring a properties you can specify which side they will be on, so `BlockStructure.blockIcons` exists on the client side but not the server side. Since minecraft uses server side even when playing locally, it's fine, but when having a server only version (dedicated server) it struggles if you're statically assigning.
